before_install:
    - yes | sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/terry_guo-gcc-arm-embedded-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
install:
    - sudo apt-get install gcc-arm-none-eabi
    - curl http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz | tar xz
    - mkdir thirdparty
    - cd thirdparty
    - curl http://static.rust-lang.org/dist/rust-nightly.tar.gz | tar xz
    - mv rust-nightly rust
    - cd ..
before_script:
    - export TOOLCHAIN_LIBS_PATH=/usr/lib/gcc/arm-none-eabi/4.8.3/
    - export RUSTC="`pwd`/rust-nightly-x86_64-unknown-linux-gnu/bin/rustc"
    - $RUSTC --version
script:
    - rake build_all
env:
    - PLATFORM=lpc17xx
    - PLATFORM=stm32f4
matrix:
  allow_failures:
    - env: PLATFORM=stm32f4
